"""&&&

Revision ID: 115ba886c02c
Revises: 0c3f5d84e23b
Create Date: 2023-08-17 18:54:16.771548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115ba886c02c'
down_revision = '0c3f5d84e23b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
