"""submenu and dish

Revision ID: 12387fda410f
Revises: 95cd4fc810fd
Create Date: 2023-08-19 21:44:58.066449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12387fda410f'
down_revision = '95cd4fc810fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
