"""aaa

Revision ID: 223cd60daf67
Revises: 8a97288e4492
Create Date: 2023-08-10 19:10:25.402994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223cd60daf67'
down_revision = '8a97288e4492'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
