"""aaa

Revision ID: 4a95300f00f9
Revises: 223cd60daf67
Create Date: 2023-08-10 19:18:48.565373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a95300f00f9'
down_revision = '223cd60daf67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
