"""&&&

Revision ID: 572950ba6af2
Revises: 7c13add768f0
Create Date: 2023-08-17 19:19:59.422863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '572950ba6af2'
down_revision = '7c13add768f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
