"""c

Revision ID: 5935ffe5ae7b
Revises: ed22446e76e2
Create Date: 2023-08-17 18:16:43.365994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5935ffe5ae7b'
down_revision = 'ed22446e76e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
