"""c

Revision ID: 64cd64c99659
Revises: 7c28f0e5f349
Create Date: 2023-08-13 16:45:45.149191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cd64c99659'
down_revision = '7c28f0e5f349'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
