"""submenu

Revision ID: 6e8ee2153913
Revises: c9a668e0f99c
Create Date: 2023-08-20 10:56:51.058045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e8ee2153913'
down_revision = 'c9a668e0f99c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
