"""&&&

Revision ID: 6f45b1e5abb5
Revises: 40c9394454b1
Create Date: 2023-08-19 10:24:07.582013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f45b1e5abb5'
down_revision = '40c9394454b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('menus', sa.Column('title', sa.String(), nullable=True))
    op.add_column('menus', sa.Column('description', sa.String(), nullable=True))
    op.drop_index('ix_menus_target_menu_description', table_name='menus')
    op.drop_index('ix_menus_target_menu_id', table_name='menus')
    op.drop_index('ix_menus_target_menu_title', table_name='menus')
    op.create_index(op.f('ix_menus_description'), 'menus', ['description'], unique=False)
    op.create_index(op.f('ix_menus_id'), 'menus', ['id'], unique=False)
    op.create_index(op.f('ix_menus_title'), 'menus', ['title'], unique=False)
    op.drop_column('menus', 'target_menu_id')
    op.drop_column('menus', 'target_menu_title')
    op.drop_column('menus', 'target_menu_description')
    op.create_foreign_key(None, 'submenus', 'menus', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submenus', type_='foreignkey')
    op.add_column('menus', sa.Column('target_menu_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('menus', sa.Column('target_menu_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('menus', sa.Column('target_menu_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_menus_title'), table_name='menus')
    op.drop_index(op.f('ix_menus_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_description'), table_name='menus')
    op.create_index('ix_menus_target_menu_title', 'menus', ['target_menu_title'], unique=False)
    op.create_index('ix_menus_target_menu_id', 'menus', ['target_menu_id'], unique=False)
    op.create_index('ix_menus_target_menu_description', 'menus', ['target_menu_description'], unique=False)
    op.drop_column('menus', 'description')
    op.drop_column('menus', 'title')
    op.drop_column('menus', 'id')
    # ### end Alembic commands ###
