"""c

Revision ID: 882b75dabdf0
Revises: 83e544688e78
Create Date: 2023-08-14 20:10:47.995039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882b75dabdf0'
down_revision = '83e544688e78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
