"""Menu, Submenu, Dish models added

Revision ID: 8a97288e4492
Revises: 8c3217811e00
Create Date: 2023-08-10 19:05:00.364222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a97288e4492'
down_revision = '8c3217811e00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
