"""wtf

Revision ID: 95cd4fc810fd
Revises: f5ce51166bc9
Create Date: 2023-08-19 15:56:10.283225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95cd4fc810fd'
down_revision = 'f5ce51166bc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
