"""c

Revision ID: 968664dccc75
Revises: 882b75dabdf0
Create Date: 2023-08-14 21:01:45.773573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968664dccc75'
down_revision = '882b75dabdf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
