"""b

Revision ID: acb3b49ad631
Revises: e5b7fe4c2ea5
Create Date: 2023-08-13 10:29:36.653721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acb3b49ad631'
down_revision = 'e5b7fe4c2ea5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_menus_description'), 'menus', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_description'), table_name='menus')
    op.drop_column('menus', 'description')
    # ### end Alembic commands ###
