"""uuid

Revision ID: ba03dca369d3
Revises: 5935ffe5ae7b
Create Date: 2023-08-17 18:26:33.949581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba03dca369d3'
down_revision = '5935ffe5ae7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
