"""c

Revision ID: bcd96529d1e0
Revises: f21192f17572
Create Date: 2023-08-17 17:55:02.849571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd96529d1e0'
down_revision = 'f21192f17572'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('price', sa.Float(precision=2), nullable=True))
    op.create_index(op.f('ix_dishes_price'), 'dishes', ['price'], unique=False)
    op.add_column('menus', sa.Column('target_menu_id', sa.Integer(), nullable=False))
    op.add_column('menus', sa.Column('target_menu_title', sa.String(), nullable=True))
    op.add_column('menus', sa.Column('target_menu_description', sa.String(), nullable=True))
    op.drop_index('ix_menus_description', table_name='menus')
    op.drop_index('ix_menus_id', table_name='menus')
    op.drop_index('ix_menus_title', table_name='menus')
    op.create_index(op.f('ix_menus_target_menu_description'), 'menus', ['target_menu_description'], unique=False)
    op.create_index(op.f('ix_menus_target_menu_id'), 'menus', ['target_menu_id'], unique=False)
    op.create_index(op.f('ix_menus_target_menu_title'), 'menus', ['target_menu_title'], unique=False)
    op.drop_column('menus', 'title')
    op.drop_column('menus', 'description')
    op.drop_column('menus', 'id')
    op.drop_constraint('submenus_menu_id_fkey', 'submenus', type_='foreignkey')
    op.create_foreign_key(None, 'submenus', 'menus', ['menu_id'], ['target_menu_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submenus', type_='foreignkey')
    op.create_foreign_key('submenus_menu_id_fkey', 'submenus', 'menus', ['menu_id'], ['id'])
    op.add_column('menus', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('menus', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('menus', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_menus_target_menu_title'), table_name='menus')
    op.drop_index(op.f('ix_menus_target_menu_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_target_menu_description'), table_name='menus')
    op.create_index('ix_menus_title', 'menus', ['title'], unique=False)
    op.create_index('ix_menus_id', 'menus', ['id'], unique=False)
    op.create_index('ix_menus_description', 'menus', ['description'], unique=False)
    op.drop_column('menus', 'target_menu_description')
    op.drop_column('menus', 'target_menu_title')
    op.drop_column('menus', 'target_menu_id')
    op.drop_index(op.f('ix_dishes_price'), table_name='dishes')
    op.drop_column('dishes', 'price')
    # ### end Alembic commands ###
