"""submenu and dish

Revision ID: c9a668e0f99c
Revises: 12387fda410f
Create Date: 2023-08-20 10:41:28.787744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a668e0f99c'
down_revision = '12387fda410f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
