"""wtf

Revision ID: df9c850a6d37
Revises: d032e7055ec6
Create Date: 2023-08-19 11:42:58.447593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9c850a6d37'
down_revision = 'd032e7055ec6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
