"""c

Revision ID: ed22446e76e2
Revises: cd43031ccfba
Create Date: 2023-08-17 18:16:34.699432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed22446e76e2'
down_revision = 'cd43031ccfba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
