"""wtf

Revision ID: f5ce51166bc9
Revises: df9c850a6d37
Create Date: 2023-08-19 15:37:45.359462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ce51166bc9'
down_revision = 'df9c850a6d37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
